### ISSUE TITLE
error when `npm run dev`

### ISSUE THREAD

**Issue by lizhiyu-me** [Chocobois/Power#1]
Uncaught TypeError: Cannot read properties of undefined (reading 'events')
    at index.js:1:38863
    at index.js:1:7239
    at index.js:1:8849
    at a (index.js:1:51763)
    at EventEmitter2.<anonymous> (index.js:1:19574)
    at EventEmitter2.emit (phaser.js?v=71e869a5:109:45)
    at DisplayList2.addChildCallback (phaser.js?v=71e869a5:17573:35)
    at Object.Add (phaser.js?v=71e869a5:136116:34)
    at DisplayList2.add (phaser.js?v=71e869a5:115940:41)
    at GameObjectFactory2.existing (phaser.js?v=71e869a5:18428:40)

**Comment by Golen87** [comment]
Thanks for reporting. Please provide the steps you did to recreate this.
